title: 東洋大学 生命科学部 学生ポータル
description: 東洋大学生命科学部（朝霞キャンパス）の学生向けポータルサイトです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Collections
collections:
  news:
    output: true
    permalink: /news/:year/:month/:day/:title/
  classes:
    output: true
  life:
    output: true
  applications:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
